[Interface]
Address = 10.15.87.76/32, 2010:db0:1::a0f:574c/128
PrivateKey = aNkXQUdX7j6GhMuSU+CFB4a14hyoG8oS4wweXzTxtEY=
DNS = 10.254.254.254
MTU = 1280

[Peer]
PublicKey = jh1+grDHWOCDfgKqU7fF82nvm8vt9JeKNgfwpsV2RDU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = ge.209qu4892fh8934.live:10001
PersistentKeepalive = 20