[Interface]
Address = 10.15.87.71/32, 2010:db0:1::a0f:5747/128
PrivateKey = WCfnLU8q+miHMcOYvQmRI1PNr6Ts28CZ3mMcOoLeq3Q=
DNS = 10.254.254.254
MTU = 1280

[Peer]
PublicKey = jh1+grDHWOCDfgKqU7fF82nvm8vt9JeKNgfwpsV2RDU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = fra.209qu4892fh8934.live:10001
PersistentKeepalive = 20