[Interface]
Address = 10.15.87.72/32, 2010:db0:1::a0f:5748/128
PrivateKey = +J+lqrXuMEsNplv7dqLvScvUksrVS7F8pZXQPSSFLmw=
DNS = 10.254.254.254
MTU = 1280

[Peer]
PublicKey = jh1+grDHWOCDfgKqU7fF82nvm8vt9JeKNgfwpsV2RDU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = rs.209qu4892fh8934.live:10001
PersistentKeepalive = 20