[Interface]
Address = 10.15.87.79/32, 2010:db0:1::a0f:574f/128
PrivateKey = KIo+JiMa+wjWfASjVwO87bWOf7QOnOhdov2KcUPXsHo=
DNS = 10.254.254.254
MTU = 1280

[Peer]
PublicKey = jh1+grDHWOCDfgKqU7fF82nvm8vt9JeKNgfwpsV2RDU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = sg.209qu4892fh8934.live:10001
PersistentKeepalive = 20